from bd_transactional.services.generic_service import GenericService
from bd_transactional.models.languedispo_model import LangueDisponible

languedisponible_service = GenericService(LangueDisponible)